### ISSUE TITLE
NoneType has no attribute 'measure'

### ISSUE THREAD

**Issue by rotten** [blaze/odo#355]
I'm trying to push a SQLAlchemy query into a DataFrame.

I've set up the session and set up a query (which works just fine).

Since I can't convert the myquery object directly into a dataframe, I thought I'd try the list object returned by myquery.all().

I get the following exception when I try it:

```
mydf = odo.odo(myquery.all(), DataFrame)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/odo/odo.py", line 90, in odo
    return into(target, source, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/into.py", line 25, in into_type
    return convert(a, b, dshape=dshape, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/core.py", line 30, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/core.py", line 46, in _transform
    x = f(x, excluded_edges=excluded_edges, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/odo/convert.py", line 170, in list_to_numpy
    return np.array(seq, dtype=dshape_to_numpy(dshape))
  File "/usr/local/lib/python2.7/site-packages/odo/numpy_dtype.py", line 60, in dshape_to_numpy
    return unit_to_dtype(ds)
  File "/usr/local/lib/python2.7/site-packages/odo/numpy_dtype.py", line 32, in unit_to_dtype
    return to_numpy_dtype(ds)
  File "/usr/local/lib/python2.7/site-packages/datashape/coretypes.py", line 1139, in to_numpy_dtype
    return to_numpy(ds.measure)[1]
AttributeError: 'NoneType' object has no attribute 'measure'
```

There is a lot of data in my result, however I'm sure some of the columns have null values here an there.   I'm not sure why ds is ending up as 'None' without spending a lot of time in the odo code.  Is it because there is a null value somewhere that it isn't expecting one?  Maybe it will be obvious to someone closer to the code here.    I'm wondering if something should catch this before it throws an exception.

I would LOVE it if I could simply call:  odo.odo(myquery, DataFrame).

odo is pretty awesome and has come in handy a few times now.  Keep up the great work!

Note:
The pandas.read_sql(myquery.statement, mysession.bind) function (as seen in several examples out there on the web) does not work for me:
   (1) It appears to create a new session to run the query - so it does not inherit previously created session variables (such as "search_path").  It also isn't going to lend itself to use in a Flask application where I'm sharing the session across threads.  It also won't work within a larger transaction.
   (2) myquery.statement does not include parameters, so it is fine for simple queries, but does not expand property for general querying.

**Comment by llllllllll** [comment]
Hey, sorry about the trouble. What version of odo are you running? This looks sort of like a bug we fixed in a recent version. Also, what is the type of `myquery.all()`?

**Comment by rotten** [comment]
$  python
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import odo
>>> odo.__version__
u'0.3.4'

>>> type(myquery.all())
<type 'list'>

Sqlalchemy query.all() returns a list of serializable row objects (they look like dictionaries when you print them).  

I just ran a 'pip install -U odo' and I didn't pick up a newer version.  :-(

Thanks for looking into it!

**Comment by rotten** [comment]
Oh, for the record, in my use case I can get a query with parameters for pandas.read_sql() by using something like this instead of a plain statement object:
str(myquery.statement.compile(compile_kwargs={"literal_binds": True}, dialect=postgresql.dialect()))

Still, point (1) with regards to session management is still an issue for me for using that approach.

**Comment by llllllllll** [comment]
hmm, the issue is that you are not feeding the query into odo for odo to execute. The user experience here is pretty bad; however, I think that this is just that odo doesn't know about the `RowProxy` type (I think you are getting `RowProxy`s here). Does `pd.DataFrame.from_records(list(map(dict, myquery.all())))` do what you want here? if so, we might just need to update the list->dataframe edge. What is the type of `myquery` without the call to `all`. If `myquery` is an instance of `sa.Selectable` you might want to try feeding that directly like odo(myquery, pd.DataFrame)`.
